version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    command: ["mongod", "--quiet", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
